export const CMS_NAME = "CMS_NAME";
export const CMS_BACKGROUND_COLOR = "CMS_BACKGROUND_COLOR";
export const TITLE_BACKGROUND_COLOR = "TITLE_BACKGROUND_COLOR";
export const TITLE_TEXT_COLOR = "TITLE_TEXT_COLOR";
export const CARD_BACKGROUND_COLOR = "CARD_BACKGROUND_COLOR";
