import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.scss";

export default function Home() {
  const projectName = "Happy Life CMS";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to {projectName}!</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Settings &rarr;</h2>
            <p>download settings file</p>
          </div>

          <div className={styles.card}>
            <h2>Db &rarr;</h2>
            <p>download project database</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://yaroslavgrushko.github.io/portfolio/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by&nbsp;
          <span className={styles.Powered}>Happy Prog</span>
        </a>
      </footer>
    </div>
  );
}
