import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.scss";
import axios from "axios";
import { useState } from "react";
import excel from "../public/images/excel.png";
import favicon from "../public/images/favicon.png";

export default function Home() {
  const [projectName, setProjectName] = useState("Happy Life CMS");

  function onSettingsSubmit(event) {
    event.preventDefault();
    var body = new FormData();
    let files_to_upload = event.target.files;

    body.append("file", files_to_upload[0]);

    axios.post("/api/flask/excelProjectSettings", body).then((response) => {
      setProjectName(response.data.cmsName);
    });
  }
  function onFaviconSubmit(event) {
    event.preventDefault();
    var body = new FormData();
    let files_to_upload = event.target.files;

    body.append("file", files_to_upload[0]);

    axios.post("/api/flask/favicon", body).then((response) => {
      console.log("favicon is updated");
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>{projectName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to {projectName}!</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Settings &rarr;</h2>
            <Image src={excel} alt="excel" style={{ width: "100%" }} />
            <form onSubmit={onSettingsSubmit}></form>
            <p>Download Settings File</p>
            <div className={styles.customFileUploadWrapper}>
              <label for="file-upload" className={styles.customFileUpload}>
                <i class="fa fa-cloud-upload"></i> &nbsp;Upload File
              </label>
            </div>
            <input
              id="file-upload"
              type="file"
              className={styles.fileUpload}
              onChange={onSettingsSubmit}
            />
          </div>

          <div className={styles.card}>
            <h2>Favicon &rarr;</h2>
            <Image src={favicon} alt="favicon" style={{ width: "100%" }} />
            <form onSubmit={onFaviconSubmit}></form>
            <p>Download Favicon</p>
            <div className={styles.customFileUploadWrapper}>
              <label for="favicon-upload" className={styles.customFileUpload}>
                <i class="fa fa-cloud-upload"></i> &nbsp;Upload File
              </label>
            </div>
            <input
              id="favicon-upload"
              type="file"
              className={styles.fileUpload}
              onChange={onFaviconSubmit}
            />
          </div>
          <div className={styles.card}>
            <h2>Db &rarr;</h2>
            <p>download project database</p>
          </div>
          <div className={styles.card}>
            <h2>Images &rarr;</h2>
            <p>download project images</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://yaroslavgrushko.github.io/portfolio/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by&nbsp;
          <span className={styles.Powered}>YG</span>
        </a>
      </footer>
    </div>
  );
}
